name: Weekly sync

on:
  workflow_dispatch:
  schedule:
  - cron: '0 0 * * 1'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: 'release'
    - name: Configuration
      run: |
        git config --local user.name "Github Action"
        git config --local user.email "enchufa2@users.noreply.github.com"
    - name: Sync with CRAN
      run: |
        Rscript pkgdb-update.r
        Rscript pkgdb-update.r
        git add pkgdb.csv
        git diff-index --quiet HEAD || git commit -m "update pkgdb"
        git push